version: "3"

services:
    backend:
        image: geanf13/backend:v1
        container_name: ClientesMock
        command: mock --cors -h 0.0.0.0 "/aos/openapi.yaml"
        ports:
          - "4010:4010"

    frontend:
        image: geanf13/frontend:v1
        container_name: ClientesUi
        ports:
            - "8000:8080"
        environment:
            SWAGGER_JSON: /aos/openapi.yaml


    proxy:
        image: geanf13/proxy:v1
        container_name: ClientesProxy
        ports:
            - "80:80"
        depends_on:
            - backend
